language: python

sudo: required

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

services:
  - docker

before_install:
  - docker pull webcenter/activemq
  - docker run -d -p 61613:61613 -e ACTIVEMQ_ENABLED_AUTH=false webcenter/activemq

install:
  - pip install -e .
  - pip install -r requirements/tests.txt
  - pip install coveralls

script: py.test -v --cov kombu_stomp --cov-report html --cov-report=term-missing tests

after_success: coveralls
