language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install:
  - pip install -e .
  - pip install -r requirements/tests.txt
  - pip install coveralls
script: py.test -v --cov kombu_stomp --cov-report html --cov-report=term-missing tests
after_success: coveralls
